baseURL = "https://JeongYunSung.github.io/"
title = "JeongYunSung"
paginate = 5
theme = "PaperMod"
enableEmoji = true
defaultContentLanguage = "ko"

[languages.ko]
languageName = "Korean"
weight = 1

[languages.ko.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.ko.menu.main]]
name = "Post"
url = "posts"
weight = 1

[[languages.ko.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.ko.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.ko.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[params]
env = "production"
author = "JeongYunSung"
comments = true
ShowToc = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "JeongYunSung"
Content = """
안녕하세요.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/JeongYunSung"

[params.editPost]
URL = "https://github.com/JeongYunSung/blog/content"
Text = "수정 제안"
appendFilePath = true